# Generated by Django 5.2.6 on 2025-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_delete_client_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuesite',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='PDF Password'),
        ),
    ]
